[package]
org = "roland"
name = "sfdc_record_update_to_gsheet_update_row"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.5"

[[dependency]]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.6"
